export const products = [
    {
        "id": 1,
        "title": "Black Shirt",
        "price": 1360,
        "category": "Men",
        "image": "/assets/black-shirt.jpg",
    },
    {
        "id": 2,
        "title": "Brown Sweater",
        "price": 1560,
        "category": "Women",
        "image": "/assets/brown-sweater.jpg",
    },    
    {
        "id": 3,
        "title": "Denims",
        "price": 1260,
        "category": "Men",
        "image": "/assets/denims.jpg",
    },    
    {
        "id": 4,
        "title": "Heels",
        "price": 2560,
        "category": "Women",
        "image": "/assets/heels.jpg",
    },    
    {
        "id": 5,
        "title": "Coat",
        "price": 3056,
        "category": "Men",
        "image": "/assets/jacket.jpg",
    },    
    {
        "id": 6,
        "title": "Coat White",
        "price": 2756,
        "category": "Women",
        "image": "/assets/jacket-white.jpg",
    },    
    {
        "id": 7,
        "title": "Ripped Jeans",
        "price": 2456,
        "category": "Women",
        "image": "/assets/jean.jpg",
    },    
    {
        "id": 8,
        "title": "Raw Denim",
        "price": 2256,
        "category": "Women",
        "image": "/assets/jeans.jpg",
    },    
    {
        "id": 9,
        "title": "White Casual Shoes",
        "price": 4356,
        "category": "Men",
        "image": "/assets/kicks.jpg",
    },    
    {
        "id": 10,
        "title": "Purple Dress",
        "price": 2156,
        "category": "Women",
        "image": "/assets/purple-dress.jpg",
    },    
    {
        "id": 11,
        "title": "Sneakers",
        "price": 3956,
        "category": "Men",
        "image": "/assets/shoes.jpg",
    },    
    {
        "id": 12,
        "title": "Black Sweater",
        "price": 1256,
        "category": "Men",
        "image": "/assets/sweater.jpg",
    },    
    {
        "id": 13,
        "title": "Sweatshirt",
        "price": 1756,
        "category": "Women",
        "image": "/assets/sweatshirt.jpg",
    },    
    {
        "id": 14,
        "title": "Tees",
        "price": 1156,
        "category": "Men",
        "image": "/assets/t-shirts.jpg",
    },    
    {
        "id": 15,
        "title": "White Dress",
        "price": 1956,
        "category": "Women",
        "image": "/assets/white-dress.jpg",
    },    
    {
        "id": 16,
        "title": "White Round Neck",
        "price": 1056,
        "category": "Women",
        "image": "/assets/white-shirt.jpg",
    },    
];